// User Actions Names 
export const SET_TUTORIAL_COMPLETE = 'TUTORIAL_COMPLETE';
export const SET_USER_AVATAR = 'SET_USER_AVATER';
export const SET_USER_PROJECT_DATA = 'SET_USER_PROJECT_DATA';
export const SET_USER_TOTAL_CLASSIFICATIONS = 'SET_USER_TOTAL_CLASSIFICATIONS';
export const SET_IS_GUEST_USER = 'SET_IS_GUEST_USER';
export const SET_USER = 'SET_USER_FROM_USER';
export const SIGN_OUT = 'SIGN_OUT';
export const SET_PUSH_PROMPTED = 'SET_PUSH_PROMPTED';

// Project Action Names
export const PROJECTS_REQUEST = 'PROJECTS_REQUEST';
export const PROJECTS_SUCCESS = 'PROJECTS_SUCCESS';
export const PROJECTS_FAILURE = 'PROJECTS_FAILURE';
export const ADD_PROJECTS = 'ADD_PROJECTS';
export const ADD_COLLABORATOR_PROJECT_ID = 'ADD_COLLABORATOR_PROJECT_ID';
export const ADD_OWNER_PROJECT_ID = 'ADD_OWNER_PROJECT_ID'

// Nav Bar Actions
export const SET_NAVBAR_TITLE = 'SET_NAVBAR_TITLE';
export const SET_NAVBAR_COLOR = 'SET_NAVBAR_COLOR';
export const SET_NAVBAR_COLOR_TO_DEFAULT = 'SET_NAVBAR_COLOR_TO_DEFAULT';

// Subject Actions
export const APPEND_SUBJECTS_TO_WORKFLOW = 'APPEND_SUBJECTS_TO_WORKFLOW'
export const CLEAR_SUBJECTS_FROM_WORKFLOW = 'CLEAR_SUBJECTS_FROM_WORKFLOW'
export const SET_SUBJECT_START_TIME = 'SET_SUBJECT_START_TIME'

// Classifier Actions
export const ADD_CLASSIFIER_TUTORIAL = 'ADD_CLASSIFIER_TUTORIAL'
export const ADD_WORKFLOW_NEEDS_TUTORIAL = 'ADD_WORKFLOW_NEEDS_TUTORIAL'
export const SET_CLASSIFIER_GUIDE = 'SET_CLASSIFIER_GUIDE'
export const INITIALIZE_ANNOTATION = 'INITIALIZE_ANNOTATION'
export const ADD_ANNOTATION_TO_TASK = 'ADD_ANNOTATION_TO_TASK'
export const REMOVE_ANNOTATION_FROM_TASK = 'REMOVE_ANNOTATION_FROM_TASK'
export const SET_SUBJECT_SEEN_THIS_SESSION = 'SET_SUBJECT_SEEN_THIS_SESSION'
export const SET_QUESTION_CONTAINER_HEIGHT = 'SET_QUESTION_CONTAINER_HEIGHT'
export const SET_CLASSIFIER_TEST_MODE = 'SET_CLASSIFIER_TEST_MODE'
export const REQUEST_CLASSIFIER_DATA = 'REQUEST_CLASSIFIER_DATA'
export const CLASSIFIER_DATA_SUCCESS = 'CLASSIFIER_DATA_SUCCESS'
export const CLASSIFIER_DATA_FAILURE = 'CLASSIFIER_DATA_FAILURE'
export const CLEAR_CLASSIFIER_DATA = 'CLEAR_CLASSIFIER_DATA'

// Image Actions
export const SAVE_IMAGE_LOCATION = 'SAVE_IMAGE_LOCATION'
export const DELETE_IMAGE_LOCATION = 'DELETE_IMAGE_LOCATION'
export const CLEAR_IMAGE_CACHE = 'CLEAR_IMAGE_CACHE'

// Settings Actions
export const ADD_PROJECT_SUBSCRIPTION = 'ADD_PROJECT_SUBSCRIPTION'
export const REMOVE_PROJECT_SUBSCRIPTION = 'REMOVE_PROJECT_SUBSCRIPTION'
export const UPDATE_SUBSCRIPTION_TO_PROJECT = 'UPDATE_SUBSCRIPTION_TO_PROJECT'
export const UPDATE_SHOW_ALL_WORKLFOWS = 'UPDATE_SHOW_ALL_WORKLFOW'
export const UPDATE_ENABLE_NOTIFICATIONS = 'UPDATE_ENABLE_NOTIFICATION'
export const UPDATE_NEW_PROJECT_NOTIICATIONS = 'UPDATE_NEW_PROJECT_NOTIICATION'
export const UPDATE_BETA_NOTIFICATIONS = 'UPDATE_BETA_NOTIFICATIONS'
export const UPDATE_URGENT_HELP_NOTIFICATIONS = 'UPDATE_URGENT_HELP_NOTIFICATIONS'
export const NOTIFICATIONS_INITIALIZED = 'NOTIFICATIONS_INITIALIZED'

// Drawing Screen Actions
export const ADD_SHAPE = 'ADD_SHAPE'
export const REMOVE_SHAPE = 'REMOVE_SHAPE'
export const MUTATE_SHAPE = 'MUTATE_SHAPE'
