// User Actions Names 
export const SYNC_USER_STORE = 'SYNC_USER_STORE';
export const SET_USER_FROM_STORE = 'SET_USER_FROM_STORE';
export const SET_TUTORIAL_COMPLETE = 'TUTORIAL_COMPLETE';
export const SET_USER_AVATAR = 'SET_USER_AVATER';
export const SET_USER_PROJECT_DATA = 'SET_USER_PROJECT_DATA';
export const SET_USER_TOTAL_CLASSIFICATIONS = 'SET_USER_TOTAL_CLASSIFICATIONS';
export const SET_IS_GUEST_USER = 'SET_IS_GUEST_USER';
export const SET_USER = 'SET_USER_FROM_USER';
export const SIGN_OUT = 'SIGN_OUT';
export const SET_PUSH_PROMPTED = 'SET_PUSH_PROMPTED';

// Project Action Names
export const PROJECTS_REQUEST = 'PROJECTS_REQUEST';
export const PROJECTS_SUCCESS = 'PROJECTS_SUCCESS';
export const PROJECTS_FAILURE = 'PROJECTS_FAILURE';
export const ADD_PROJECTS = 'ADD_PROJECTS';
export const ADD_COLLABORATOR_PROJECT_ID = 'ADD_COLLABORATOR_PROJECT_ID';
export const ADD_OWNER_PROJECT_ID = 'ADD_OWNER_PROJECT_ID'

// Nav Bar Actions
export const SET_NAVBAR_TITLE = 'SET_NAVBAR_TITLE';
export const SET_NAVBAR_COLOR = 'SET_NAVBAR_COLOR';
export const SET_NAVBAR_COLOR_TO_DEFAULT = 'SET_NAVBAR_COLOR_TO_DEFAULT';