project './ZooniverseMobile.xcodeproj'

target 'ZooniverseMobile' do
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'SocketRocket'
  pod 'HockeySDK'
  pod 'react-native-blur', :path => '../node_modules/react-native-blur'

end
