project './ZooniverseMobile.xcodeproj'

target 'ZooniverseMobile' do
  pod 'Firebase/Core'
  pod 'SocketRocket'
  pod 'Firebase/Messaging', '~> 5.15.0'




  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end
