# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
require 'semantic'

default_platform(:ios)

platform :ios do
  
  desc "Push a new beta build to TestFlight"
  lane :beta do |options|
    # Download provisioning profiles
    match(type: "appstore", git_url: "git@github.com:zooniverse/mobile-provisioning-profiles.git" )

    # Update Version 
    old_version_string = get_info_plist_value(path: "./ZooniverseMobile/Info.plist", key: "CFBundleShortVersionString")
    old_version = Semantic::Version.new(old_version_string)
    new_version = old_version.increment!(options[:increment_type])
    UI.message("Building the iOS app with version number: #{new_version}")
    set_info_plist_value(path: "./ZooniverseMobile/Info.plist", key: "CFBundleShortVersionString", value: new_version.to_s)

    # Build and deploy
    build_app(workspace: "ZooniverseMobile.xcworkspace", scheme: "ZooniverseMobile")
    upload_to_testflight
  end
  
end
