# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
require 'semantic'
default_platform(:android)

platform :android do

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do |options|
    # Increment the version code
    android_set_version_code(gradle_file: "app/build.gradle")
    
    # Increment the version name
    old_version_string = android_get_version_name(gradle_file: "app/build.gradle")
    old_version = Semantic::Version.new(old_version_string)
    new_version = old_version.increment!(options[:increment_type])
    UI.message("Building the Android app with version number: #{new_version}")
    android_set_version_name(version_name: new_version.to_s, gradle_file: "app/build.gradle")

    # Build and deploy
    # gradle(task: "clean assembleRelease")
    # upload_to_play_store(track: "beta")
  end
end
